services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_volume: